name: CI 
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python, pipenv, and dependencies
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pipenv install --dev

      - name: Run tests
        run: |
          pipenv run pytest --tb=short --disable-warnings
